In [16]:
import pandas as pd
df_cyling = pd.read_csv('/home/jann/Platzi/DataScience/CourseNumpyAndPandasBasic/stages_TDF (1).csv')
df_cyling[:5]

,Stage,Date,Distance,Origin,Destination,Type,Winner,Winner_Country
0,1,2017-07-01,14.0,Düsseldorf,Düsseldorf,Individual time trial,Geraint Thomas,GBR
1,2,2017-07-02,203.5,Düsseldorf,Liège,Flat stage,Marcel Kittel,GER
2,3,2017-07-03,212.5,Verviers,Longwy,Medium mountain stage,Peter Sagan,SVK
3,4,2017-07-04,207.5,Mondorf-les-Bains,Vittel,Flat stage,Arnaud Démare,FRA
4,5,2017-07-05,160.5,Vittel,La Planche des Belles Filles,Medium mountain stage,Fabio Aru,ITA

## __Mayores a cierto valor.__

In [19]:
mayor_150km = df_cyling["Distance"] > 150

0       False
1        True
2        True
3        True
4        True
        ...
2231     True
2232     True
2233     True
2234     True
2235     True
Name: Distance, Length: 2236, dtype: bool

In [20]:
df_cyling[mayor_150km]

,Stage,Date,Distance,Origin,Destination,Type,Winner,Winner_Country
1,2,2017-07-02,203.5,Düsseldorf,Liège,Flat stage,Marcel Kittel,GER
2,3,2017-07-03,212.5,Verviers,Longwy,Medium mountain stage,Peter Sagan,SVK
3,4,2017-07-04,207.5,Mondorf-les-Bains,Vittel,Flat stage,Arnaud Démare,FRA
4,5,2017-07-05,160.5,Vittel,La Planche des Belles Filles,Medium mountain stage,Fabio Aru,ITA
5,6,2017-07-06,216.0,Vesoul,Troyes,Flat stage,Marcel Kittel,GER
...,...,...,...,...,...,...,...,...
2231,2,1903-07-05,374.0,Lyon,Marseille,Stage with mountain(s),Hippolyte Aucouturier,FRA
2232,3,1903-07-08,423.0,Marseille,Toulouse,Plain stage,Hippolyte Aucouturier,FRA
2233,4,1903-07-12,268.0,Toulouse,Bordeaux,Plain stage,Charles Laeser,SUI
2234,5,1903-07-13,425.0,Bordeaux,Nantes,Plain stage,Maurice Garin,FRA
2235,6,1903-07-18,471.0,Nantes,Paris,Plain stage,Maurice Garin,FRA

In [27]:
col_nationality = df_cyling["Winner_Country"] ==  "COL"
df_cyling[col_nationality & (df_cyling["Distance"] > 200) ]

,Stage,Date,Distance,Origin,Destination,Type,Winner,Winner_Country
330,15,2002-07-23,226.5,Vaison-la-Romaine,Les Deux Alpes,Hilly stage,Santiago Botero,COL
370,14,2000-07-15,249.5,Draguignan,Briançon,Stage with mountain(s),Santiago Botero,COL
454,11,1996-07-11,202.0,Gap,Valence,Hilly stage,José Jaime Gonzalez,COL
523,15,1993-07-19,231.5,Perpignan,Pal,Stage with mountain(s),Oliverio Rincón,COL
629,11,1988-07-13,232.0,Besançon,Morzine,Stage with mountain(s),Fabio Parra,COL
703,12,1985-07-10,269.0,Morzine Avoriaz,Lans-en-Vercors,Stage with mountain(s),Fabio Parra,COL